export const articleData = [
    {
        category: 'Blog Category 1',
        date: '00 Month, 2022',
        imageSrc: 'assests/section/section3.png',
        title: 'Article Title 1',
        content: 'Lorem ipsum Lorem ipsum dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt.dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt...',
    },
    {
        category: 'Blog Category 2',
        date: '00 Month, 2022',
        imageSrc: 'assests/section/section3.png',
        title: 'Article Title 2',
        content: 'Lorem ipsum Lorem ipsum dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt.dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt...',
    },
    {
        category: 'Blog Category 3',
        date: '00 Month, 2022',
        imageSrc: 'assests/section/section3.png',
        title: 'Article Title 3',
        content: 'Lorem ipsum Lorem ipsum dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt.dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt...',
    },
    {
        category: 'Blog Category 1',
        date: '00 Month, 2022',
        imageSrc: 'assests/section/section3.png',
        title: 'Article Title 1',
        content: 'Lorem ipsum Lorem ipsum dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt.dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt...',
    },
    {
        category: 'Blog Category 2',
        date: '00 Month, 2022',
        imageSrc: 'assests/section/section3.png',
        title: 'Article Title 2',
        content: 'Lorem ipsum Lorem ipsum dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt.dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt...',
    },
    {
        category: 'Blog Category 3',
        date: '00 Month, 2022',
        imageSrc: 'assests/section/section3.png',
        title: 'Article Title 3',
        content: 'Lorem ipsum Lorem ipsum dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt.dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt...',
    },
    {
        category: 'Blog Category 1',
        date: '00 Month, 2022',
        imageSrc: 'assests/section/section3.png',
        title: 'Article Title 1',
        content: 'Lorem ipsum Lorem ipsum dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt.dolor sit amet, consectetuer adipiscing Lorem ipsum dolor sit amet, consectetuer adipiscing elit,elit, sed diam nonummy nibh euismod tincidunt...',
    },
];